sudo: false
dist: trusty

language: bash

services:
  - docker

jobs:
  include:
    - stage: test
      script: make test
    - stage: deploy
      script: make build
      if: branch = master
    - stage: daily-deploy
      script: make build-all
      if: type = cron

fast_finish: true