sudo: false
dist: trusty

language: bash

services:
  - docker

jobs:
  include:
    - stage: test
      script: ./test.sh
      if: type != cron
    - stage: deploy
      script: ./build.sh
      if: type != cron
    - stage: daily-deploy
      script: ./build-all.sh
      if: type = cron

fast_finish: true